### ISSUE TITLE
CNOE logo are gone, no template is proposed like component

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/backstage-app#14]
## TODO

- [ ] CNOE logo are gone (see screenshot), 
- [ ] No template is proposed OOTB
- [ ] No "dummy/example" component is registered by default

![Screenshot 2024-03-13 at 19 04 41](https://github.com/cnoe-io/backstage-app/assets/463790/8b186a48-2899-47e1-b33f-ebc205304be9)

**Comment by jessesanford** [comment]
I am seeing this now as well.

**Comment by OneCricketeer** [comment]
Assuming this is after using https://github.com/cnoe-io/stacks/tree/main/ref-implementation then I also see nothing here
